### ISSUE TITLE
[Question] Would it be a good idea to make the markdown images base64 as well?

### ISSUE THREAD

**Issue by TFWol** [CurtisDS/minified-civitai#1]
The script has worked very well so far. Thanks for sharing!

I have a question about the choice of using direct url references in the .md files as opposed to Base64.
Would your model preview extension break if base64 were used in markdown?

**Comment by CurtisDS** [comment]
Markdown is not 100% standardized. Some things work for one viewer but don't for another and unfortunately support for base64 images is one of those things. If you are using some other viewer it might work but in gradio's markdown it does not. At least as far as I could tell.

**Comment by TFWol** [comment]
Understood. Thanks for explaining. 
Btw, very nice layout with the html.

**Comment by TFWol** [comment]
Nice, I just tried it with a test. It looks like Base64 renders. 
I took a glob from the html and put it in `![image](data:image/JPEG;base64,base64text)`

**Comment by CurtisDS** [comment]
Interesting. So two things. The bit of code I tried when I was testing if base64 strings would work... didnt work... but maybe the string I got from stackoverflow was corrupt or something. I just tested it with another string that I know is good and it worked. So I can update the code to use base64 strings.

Secondly... I was originally targeting markdown that would work with rentry.org (I wrote this script before the preview models extension was a thing). But gradio actually seems to support html tags... or at least a few anyway. So I am actually considering changing it to an `<img>` tag because that works AND lets you set a height and width.

So ill have another go at designing the markdown output. It might be a bit more of a hybrid of html and markdown but I will probably be able to make it look nicer than pure markdown.

**Comment by TFWol** [comment]
Glad to see you're finding some things of interest 😃

**Comment by CurtisDS** [comment]
- Redid the markdown and added a little html to it so it looks nicer in automatic1111. Hopefully it still keeps to the markdown spirit.
- Left in the original markdown intended for rentry.org if you use --md-legacy as an argument.
- By default it will convert images to base64 strings for markdown and html files now.
- You can also use --no-base64-images to have it output with normal links instead.

**Comment by TFWol** [comment]
This works amazing. The only thing I have to tweak are the colors in .md since the comments and some headers aren't easy to read (prob since I use dark theme), but that's easy for me to manually do.

It's pretty crazy to see how professional your code looks; I'm used to things being slapped together.
